apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
    project: improve-service

spec:
  #Added Two Replicas
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: komodor-oomkilled
        #Ensure there is a VERSION on the Image Tag. Not Latest or Emtpy
        image: polinux/stress:1.0.4
        #Set ImagePull to Always
        imagePullPolicy: Always
        # Ensure Security Context Exists and has a minimum configurtion. No running Containers as ROOT
        # Ensure Correct Security Context
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        command: ["/bin/sh", "-c"]
        args: ["echo 'Going to allocate 100MB of memory!'; stress --vm 2 --vm-bytes 30M --vm-hang 120 --backoff 10000000 --verbose"]
        # Ensure Limits are Set
        resources:
          requests:
            memory: "40Mi"
            cpu: 250m
          limits:
            memory: "100Mi"
            cpu: 500m
        # Install Liveness
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          exec:
            command:
              - ls
              - /tmp
        # Install Readiness Probes
        readinessProbe:
          exec:
            command:
              - ls
              - /tmp
          initialDelaySeconds: 5
          periodSeconds: 5