apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-service
  namespace: optimization-single-application
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/d2983e7615f45fee8e389fb60d902e9b8bec602d
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: d2983e7615f45fee8e389fb60d902e9b8bec602d

  labels:
    app: red-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: red-service
  template:
    metadata:
      labels:
        app: red-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: ["echo 'Going to allocate 100MB of memory!' ; stress --vm 2 --vm-bytes 50M --vm-hang 60 --backoff 10000000 --verbose"]
        resources:
          requests:
            memory: "55Mi"
          limits:
            memory: "102Mi"