apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-service
  namespace: optimization-colors-applications
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/d2983e7615f45fee8e389fb60d902e9b8bec602d
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: d2983e7615f45fee8e389fb60d902e9b8bec602d

  labels:
    app: yellow-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow-service
  template:
    metadata:
      labels:
        app: yellow-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: ["echo 'Going to allocate 100MB of memory!' ; stress --cpu 2 --vm 2 --vm-bytes 50M --vm-hang 60 --backoff 10000000 --verbose"]
        resources:
          requests:
            memory: "110Mi"
          limits:
            memory: "125Mi"