apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-service
  namespace: color-optimize
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/1466d6a9c2055394d01aeefb2b9375a2d49fff9a
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: 1466d6a9c2055394d01aeefb2b9375a2d49fff9a

  labels:
    app: blue-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-service
  template:
    metadata:
      labels:
        app: blue-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: [$(CMD_ARGS)]
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: CMD_ARGS
          valueFrom:
            configMapKeyRef:
              name: cpu-memory-settings
              key: blue-args
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          exec:
            command:
              - ls
              - /tmp
        # Install Readiness Probes
        readinessProbe:
          exec:
            command:
              - ls
              - /tmp
          initialDelaySeconds: 5
          periodSeconds: 5
