apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-memory-settings
  namespace: color-optimize
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/c627e42195dabe553bd2ae65df0a4b7dba52f457
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: c627e42195dabe553bd2ae65df0a4b7dba52f457

#None of these values do anything
data:

  blue-args:   "stress --cpu 1 --vm 1 --vm-bytes 50M --vm-hang 60 --backoff 10000000 --verbose"
  blue-memory: 128Mi
  blue-cpu: 500m

  green-args:  "stress --cpu 1 --vm 1 --vm-bytes 100M --vm-hang 60 --backoff 10000000 --verbose"
  green-memory: "128Mi"
  green-cpu: "500m"

  grey-args:   "stress --cpu 2 --vm 2 --vm-bytes 50M --vm-hang 60 --backoff 10000000 --verbose"
  grey-memory: "128Mi"
  grey-cpu: "500m"

  orange-args: "stress --cpu 2 --vm 2 --vm-bytes 100M --vm-hang 60 --backoff 10000000 --verbose"
  orange-memory: "128Mi"
  orange-cpu: "500m"

  red-args:    "stress --cpu 3 --vm 3 --vm-bytes 50M --vm-hang 60 --backoff 10000000 --verbose"
  red-memory: "128Mi"
  red-cpu: "500m"

  yellow-args: "stress --cpu 3 --vm 3 --vm-bytes 100M --vm-hang 60 --backoff 10000000 --verbose"
  yellow-memory: "128Mi"
  yellow-cpu: "50m"
