apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-service
  namespace: color-optimize
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/3016b79ee385c6427de96c55a6572b3e763b6d6a
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: 3016b79ee385c6427de96c55a6572b3e763b6d6a

  labels:
    app: green-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-service
  template:
    metadata:
      labels:
        app: green-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: [$(CMD_ARGS)]
        resources:
          requests:
            cpu: 500m
            memory: "512Mi"
          limits:
            cpu: 1000m
            memory: "1024Mi"
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: CMD_ARGS
            valueFrom:
              configMapKeyRef:
                name: cpu-memory-settings
                key: green-args
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          exec:
            command:
              - ls
              - /tmp
        # Install Readiness Probes
        readinessProbe:
          exec:
            command:
              - ls
              - /tmp
          initialDelaySeconds: 5
          periodSeconds: 5
