apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-service
  namespace: color-optimize
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/d2983e7615f45fee8e389fb60d902e9b8bec602d
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: d2983e7615f45fee8e389fb60d902e9b8bec602d

  labels:
    app: green-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-service
  template:
    metadata:
      labels:
        app: green-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: [$(CMD_ARGS)]
        resources:
          requests:
            cpu: $(CPU)
            memory: $(MEMORY)
          limits:
            cpu: 1000m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: CMD_ARGS
            valueFrom:
              configMapKeyRef:
                name: cpu-memory-settings
                key: green-args
          - name: CPU
            valueFrom:
              configMapKeyRef:
                name: cpu-memory-settings
                key: green-memory
          - name: MEMORY
            valueFrom:
              configMapKeyRef:
                name: cpu-memory-settings
                key: green-cpu