apiVersion: apps/v1
kind: Deployment
metadata:
  name: grey-service
  namespace: color-optimize
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing

  labels:
    app: grey-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grey-service
  template:
    metadata:
      labels:
        app: grey-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: [$(CMD_ARGS)]
        resources:
          requests:
            cpu: 500m
            memory: "128Mi"
          limits:
            cpu: 1000m
            memory: "128Mi"
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: CMD_ARGS
            valueFrom:
              configMapKeyRef:
                name: cpu-memory-settings
                key: grey-args