apiVersion: apps/v1
kind: Deployment
metadata:
  name: grey-service
  namespace: color-optimize
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing

  labels:
    app: grey-service
    feature: cost-optimization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grey-service
  template:
    metadata:
      labels:
          app: grey-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["/bin/sh", "-c"]
        args: [$(CMD_ARGS)]
        resources:
          requests:
            memory: "1024Mi"
            cpu: 500m
          limits:
            memory: "2048Mi"
            cpu: 1000m
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
          - name: CMD_ARGS
            valueFrom:
              configMapKeyRef:
                name: cpu-memory-settings
                key: grey-args
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          exec:
            command:
              - ls
              - /tmp
        # Install Readiness Probes
        readinessProbe:
          exec:
            command:
              - ls
              - /tmp
          initialDelaySeconds: 5
          periodSeconds: 5