apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  annotations:
    app.komodor.com/service.link.webhook: http://35.202.170.30:5000/version
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.webhook: http://35.202.170.30:5000/version
    app.komodor.com/deploy.link.github-latestchange: https://github.com/hughbrien/optimization_testing/commit/d7726b24c32668fe10b545f378056ef5aa8dc025
    app.komodor.com/tracked_files: |
      *.yaml
    app.komodor.com/app: https://github.com/hughbrien/optimization_testing
    app.komodor.com/app.ref: d7726b24c32668fe10b545f378056ef5aa8dc025

  labels:
    app: catalog-service
    branch: main
    version: 2.1.1
    author: hughbrien
    notes: 2.1.1
    owner: hughbrien

spec:
  selector:
    matchLabels:
      app: catalog-service
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-service
        branch: main
        version: 2.1.1
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          limits:
            cpu: 500m
            memory: 512M
          requests:
            cpu: 250m
            memory: 256M