apiVersion: v1
kind: Namespace
metadata:
  name: optimization-testing
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: optimization-testing
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
