apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  annotations:
    app.komodor.com/service.link.github: https://github.com/hughbrien/optimization_testing
    app.komodor.com/deploy.link.github: https://github.com/hughbrien/optimization_testing
  labels:
    app: pricing-service
    branch: main
    version: 2.1.1
    author: hughbrien
    withExtraSecurity: ENABLED
spec:
  selector:
    matchLabels:
      app: pricing-service
  replicas: 1
  template:
    metadata:
      labels:
        app: pricing-service
        branch: main
        version: 2.1.1
    spec:
      containers:
      - name: frontend
        image: docker.io/hughbrien/frontend:2.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        resources:
          requests:
            cpu: 500m
            memory: 300Mi
          limits:
            cpu: 750m
            memory: 400Mi