apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress:1.0.4
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        command: ["/bin/sh", "-c"]
        args: ["echo 'Going to allocate 100MB of memory!'; stress --vm 2 --vm-bytes 30M --vm-hang 120 --backoff 10000000 --verbose"]
        resources:
          requests:
            memory: "40Mi"
            cpu: 250m
          limits:
            memory: "100Mi"
            cpu: 500m
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          exec:
            command:
              - ls
              - /tmp
        readinessProbe:
          exec:
            command:
              - ls
              - /tmp
          initialDelaySeconds: 5
          periodSeconds: 5
